# Generated by Django 5.1.3 on 2024-12-17 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 3, 39, 46, 949847, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
