# Generated by Django 5.1.3 on 2024-12-17 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_postdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
