# Generated by Django 5.1.3 on 2024-12-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postdb_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='categories',
            field=models.ManyToManyField(related_name='get_posts', to='blog.categorydb', verbose_name='Categorias'),
        ),
    ]
