# Generated by Django 5.1.3 on 2024-12-21 03:10

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagedb_options_pagedb_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedb',
            name='contents',
            field=froala_editor.fields.FroalaField(verbose_name='Contenido'),
        ),
    ]
